### ISSUE TITLE
Support for multiple environments

### ISSUE THREAD

**Issue by husseycoding** [ctidigital/magento-configurator#13]
In a multi environment setup you often want to have different confirguration options for the different environments.  For instance in production you might want analytics enabled, but in staging you don't, or perhaps in production you want the main paypal account configured, but in staging you want a sandbox account configured instead.

**Comment by husseycoding** [comment]
I actually just watched the original presentation about configurator, and the presenter does mention support for multiple environments with an example file of 'local.config.yaml' which should be symlinked to another envronment specific config file with config settings just for that environment.  This was some time ago though so not sure if it's still supported or not?

**Comment by chevli** [comment]
Hi @husseycoding,

Yes this is supported and you will require to maintain a _local_ `config.yaml` per environment. We would usually symlink/copy the file on build/deploy and run configurator. The _local_ `config.yaml` will require to be placed in `app/etc/local_components/config.yaml`. https://github.com/ctidigital/magento-configurator/blob/master/src/app/code/community/Cti/Configurator/Helper/Components/Config.php#L10.

This should allow you to specify environment specific configurations.

Thanks

**Comment by husseycoding** [comment]
Great!  Does this extend to other components or just the config?

**Comment by chevli** [comment]
It also extends to the media and sql component and it shouldn't be difficult to include these in the other components by including the same merging of yaml array code.

**Comment by husseycoding** [comment]
Thanks for the info.
